### PR TITLE
add calculator

### PR DESCRIPTION
**Pull request by ankit060801**

### CODE REVIEW

**Comment by avincodes** [comment]
I'm sorry but this issue is already assigned to someone and they are working on it, it is unfair to them if I accept your PR! I will however not close this, and if the person who is assigned fails to submit a PR in the next 24 hours, will accept this! Hope you can understand @ankit060801!

**Comment by ankit060801** [comment]
@avincodes ok sir no issue

**Comment by avincodes** [comment]
Also, you can call me bro or Avin, you don't have to call me sir! Haha! 😅

**Comment by ankit060801** [comment]
okay @avincodes

**Comment by ankit060801** [comment]
@avincodes here it is showing no one assigned

**Comment by avincodes** [comment]
This is the pull request you opened, assignees are shown on the issue!  #70

**Pull request merged**
